# Generated by Django 4.2.20 on 2025-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
