# Generated by Django 4.2.20 on 2025-04-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudos',
            name='headline',
            field=models.CharField(default='Hardwork', max_length=20),
        ),
    ]
