# Generated by Django 4.2.20 on 2025-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos_app', '0003_kudos_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='headline',
            field=models.CharField(max_length=20),
        ),
    ]
